/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_1 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg z,
    output reg v,
    output reg n,
    output reg [7:0] out
  );
  
  
  
  wire [8-1:0] M_adder_sum;
  reg [8-1:0] M_adder_a;
  reg [8-1:0] M_adder_b;
  reg [6-1:0] M_adder_alufn;
  adder_7 adder (
    .a(M_adder_a),
    .b(M_adder_b),
    .alufn(M_adder_alufn),
    .sum(M_adder_sum)
  );
  
  wire [1-1:0] M_zvn_z;
  wire [1-1:0] M_zvn_v;
  wire [1-1:0] M_zvn_n;
  reg [6-1:0] M_zvn_alufn;
  reg [8-1:0] M_zvn_a;
  reg [8-1:0] M_zvn_b;
  zvn_8 zvn (
    .alufn(M_zvn_alufn),
    .a(M_zvn_a),
    .b(M_zvn_b),
    .z(M_zvn_z),
    .v(M_zvn_v),
    .n(M_zvn_n)
  );
  
  wire [8-1:0] M_shifter_shift;
  reg [6-1:0] M_shifter_alufn;
  reg [8-1:0] M_shifter_a;
  reg [8-1:0] M_shifter_b;
  shifter8_9 shifter (
    .alufn(M_shifter_alufn),
    .a(M_shifter_a),
    .b(M_shifter_b),
    .shift(M_shifter_shift)
  );
  
  wire [8-1:0] M_compare_cmp;
  reg [1-1:0] M_compare_z;
  reg [1-1:0] M_compare_v;
  reg [1-1:0] M_compare_n;
  reg [6-1:0] M_compare_alufn;
  compare8_10 compare (
    .z(M_compare_z),
    .v(M_compare_v),
    .n(M_compare_n),
    .alufn(M_compare_alufn),
    .cmp(M_compare_cmp)
  );
  
  wire [8-1:0] M_boolean_boole;
  reg [6-1:0] M_boolean_alufn;
  reg [8-1:0] M_boolean_a;
  reg [8-1:0] M_boolean_b;
  boolean_11 boolean (
    .alufn(M_boolean_alufn),
    .a(M_boolean_a),
    .b(M_boolean_b),
    .boole(M_boolean_boole)
  );
  
  always @* begin
    M_adder_a = a;
    M_adder_b = b;
    M_adder_alufn = alufn;
    M_zvn_a = a;
    M_zvn_b = b;
    M_zvn_alufn = alufn;
    M_boolean_a = a;
    M_boolean_b = b;
    M_boolean_alufn = alufn;
    M_shifter_a = a;
    M_shifter_b = b;
    M_shifter_alufn = alufn;
    M_compare_z = M_zvn_z;
    M_compare_v = M_zvn_v;
    M_compare_n = M_zvn_n;
    M_compare_alufn = alufn;
    z = M_zvn_z;
    v = M_zvn_v;
    n = M_zvn_n;
    
    case (alufn[4+1-:2])
      2'h0: begin
        out = M_adder_sum;
      end
      2'h1: begin
        out = M_boolean_boole;
      end
      2'h2: begin
        out = M_shifter_shift;
      end
      2'h3: begin
        out = M_compare_cmp;
      end
      default: begin
        out = 8'h00;
      end
    endcase
  end
endmodule
