/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module numbersDisplay_6 (
    input [3:0] score,
    output reg [6:0] digitDisplay
  );
  
  
  
  always @* begin
    digitDisplay = 7'h00;
    
    case (score)
      4'h0: begin
        digitDisplay = 7'h77;
      end
      4'h1: begin
        digitDisplay = 7'h44;
      end
      4'h2: begin
        digitDisplay = 7'h3e;
      end
      4'h3: begin
        digitDisplay = 7'h6e;
      end
      4'h4: begin
        digitDisplay = 7'h4d;
      end
      4'h5: begin
        digitDisplay = 7'h6b;
      end
      4'h6: begin
        digitDisplay = 7'h7b;
      end
      4'h7: begin
        digitDisplay = 7'h46;
      end
      4'h8: begin
        digitDisplay = 7'h7f;
      end
      4'h9: begin
        digitDisplay = 7'h6f;
      end
      4'he: begin
        digitDisplay = 7'h00;
      end
      4'hf: begin
        digitDisplay = 7'h08;
      end
    endcase
  end
endmodule
